### ISSUE TITLE
Observation Space Misspecified?

### ISSUE THREAD

**Issue by AmineElhafsi** [jakegrigsby/dmc_remastered#2]
Hello,

Thanks for the repo!

I was trying to set up a simple cartpole (swing up) environment and noticed that the observation space is specified with a range from 0 to 1 [here](https://github.com/jakegrigsby/dmc_remastered/blob/544d43e4542a320f8089f8fcd1ae31e9b5755af6/dmc_remastered/wrapper.py#L19C9-L24C10) as uint8. However, the actual observations are in the range 0 to 255. Am I misusing the environment wrapper or is this a bug?

**Comment by jakegrigsby** [comment]
Hi, thanks! That's just a bug created by the fact that none of my RL code checks the upper and lower bounds of the observation space and assumes it's always [-inf, inf]. The framestack wrapper also works for state-based observations which are float32. Should be fixed now!

**Comment by AmineElhafsi** [comment]
I see - thanks!
